# Generated by Django 3.0.5 on 2020-04-18 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='car_name',
            new_name='Drivers_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='employee_name',
            new_name='license_number',
        ),
    ]
