# Generated by Django 3.0.5 on 2020-04-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='user_tran',
            field=models.IntegerField(default=0),
        ),
    ]
