# Generated by Django 3.0.5 on 2020-04-30 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20200430_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='hours',
            field=models.IntegerField(default=0),
        ),
    ]
