# Generated by Django 3.0.5 on 2020-04-18 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='name',
            new_name='loc_name',
        ),
    ]
