# Generated by Django 3.0.5 on 2020-04-30 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_booking_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='startsubscribe',
            name='acc',
            field=models.IntegerField(default=400),
            preserve_default=False,
        ),
    ]
