# Generated by Django 3.0.5 on 2020-04-20 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_auto_20200418_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='loc_zip',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
