# Generated by Django 3.0.5 on 2020-04-20 05:13

from django.db import migrations, models
import system.models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_location_loc_zip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='company_name',
            new_name='reg_tag',
        ),
        migrations.RemoveField(
            model_name='car',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='car',
            name='width_field',
        ),
        migrations.AddField(
            model_name='car',
            name='car_type',
            field=models.CharField(choices=[('small car', 'SMALL CAR'), ('full-size_car', 'FULL-SIZE CAR'), ('truck', 'TRUCK'), ('luxury', 'LUXURY')], default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='cur_milage',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='last_serv',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=system.models.uploaded_location),
        ),
    ]
