# Generated by Django 3.0.5 on 2020-04-20 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_userdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='mobileno',
            field=models.IntegerField(),
        ),
    ]
