# Generated by Django 3.0.5 on 2020-04-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_start_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='start_subscription',
            name='credit_card_number',
            field=models.IntegerField(),
        ),
    ]
