# Generated by Django 3.0.5 on 2020-04-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_auto_20200420_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='vehicle_cond',
            field=models.CharField(choices=[('Good', 'Good'), ('Need Cleaning', 'Need Cleaning'), ('Needs Maintenance', 'Need Maintenance')], max_length=100),
        ),
    ]
