# Generated by Django 3.0.5 on 2020-04-20 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_auto_20200420_0947'),
        ('system', '0008_auto_20200420_0603'),
    ]

    operations = [
    ]
