# Generated by Django 3.0.5 on 2020-04-20 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_merge_20200420_1739'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='start_subscription',
            new_name='StartSubscribe',
        ),
    ]
