# Generated by Django 3.0.5 on 2020-04-21 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_auto_20200420_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='startsubscribe',
            name='first_name',
            field=models.CharField(default='sri12', max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='Drivers_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='first_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
