# Generated by Django 3.0.5 on 2020-04-21 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_merge_20200421_0051'),
        ('system', '0011_auto_20200421_0149'),
    ]

    operations = [
    ]
