# Generated by Django 3.0.5 on 2020-04-23 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0013_auto_20200423_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='depot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='vehicle', to='system.Location'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='rent_loc',
            field=models.CharField(max_length=50),
        ),
    ]
