# Generated by Django 3.0.5 on 2020-04-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0014_auto_20200423_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='vehicle_cap1',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
