# Generated by Django 3.0.5 on 2020-04-23 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0015_location_vehicle_cap1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='vehicle_cap1',
        ),
    ]
