# Generated by Django 3.0.5 on 2020-04-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0016_remove_location_vehicle_cap1'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='vehicle_cap1',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
