# Generated by Django 3.0.5 on 2020-04-23 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0018_remove_location_vehicle_cap1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='rent_loc',
            new_name='zipcode',
        ),
    ]
